version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - ./backend/config.json:/app/config.json
    command: ["/kubecloud", "--config", "/app/config.json"]
