apiVersion: v1
kind: Pod
metadata:
  name: test-server
  labels:
    app: test-server
spec:
  containers:
    - name: python-http
      image: python:3.12
      command: ["python", "-m", "http.server", "8000", "--bind", "0.0.0.0"]
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: test-server-svc
spec:
  type: LoadBalancer
  selector:
    app: test-server
  ports:
    - port: 80
      targetPort: 8000
