name: Build & Push Docker Images

on:
  push:
    branches: [ master ]
    paths:
      - 'kubecloud/backend/**'
      - 'kubecloud/frontend/kubecloud/**'
      - '.github/workflows/docker-build.yaml'
  pull_request:
    paths:
      - 'kubecloud/backend/**'
      - 'kubecloud/frontend/kubecloud/**'
      - '.github/workflows/docker-build.yaml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional release tag (e.g. v1.2.3)'
        required: false
        type: string

# Build only amd64 and push to GHCR
env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: backend
            context: kubecloud/backend
            dockerfile: kubecloud/backend/Dockerfile
            image: kubecloud-backend
          - name: frontend
            context: kubecloud/frontend/kubecloud
            dockerfile: kubecloud/frontend/kubecloud/Dockerfile
            image: kubecloud-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize owner to lowercase for GHCR
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up QEMU (for completeness)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/${{ matrix.image }}
          flavor: |
            latest=true
          tags: |
            type=sha
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            ${{ inputs.tag && format('type=raw,value={0}', inputs.tag) || '' }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build & Push (amd64 only)
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/${{ matrix.context }}
          file: ${{ github.workspace }}/${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Summary
        run: |
          echo "Built ghcr.io/${OWNER_LC}/${{ matrix.image }}" >> $GITHUB_STEP_SUMMARY
          echo "Tags:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" | sed 's/,/
/g' >> $GITHUB_STEP_SUMMARY
