name: Vue lint
on:
  push:
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./frontend/kubecloud/package-lock.json
      - name: npm Install
        run: cd frontend/kubecloud && npm install
      - name: ESLint
        run: cd frontend/kubecloud && npm run lint
